name: Run Go Files and Generate Output
on: workflow_dispatch
inputs:
  branch:
    description: 'Branch to be fetched'
    required: true
  batch:
    description: 'Batch to be fetched'
    required: true

jobs:
  run-go-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'


      - name: Build and run fetch_result.go
        run: go run scrape/cmd/fetch_result.go

      - name: Build and run gen_json.go
        run: go run scrape/cmd/gen_json.go

      - name: Save output files
        uses: actions/upload-artifact@master
        with:
          name: ranks_result.json
          path: ranks_result.json


      - name: Save output files
        uses: actions/upload-artifact@master
        with:
          name: detailed_result.json
          path: detailed_result.json

      - name: Save output files
        uses: actions/upload-artifact@master
        with:
          name: result_config.json
          path: result_config.json

      - name: Save output files
        uses: actions/upload-artifact@master
        with:
          name: result.db
          path: scrape/result.db
