name: Run Go Files and Generate Output
on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'Batch to fetch, valid values in fetch_result.go'
        required: true
        default: ''


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  run-go-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'


      - name: Build and run fetch_result.go
        run: cd scrape && go run cmd/fetch_result.go '${{ github.event.inputs.batch }}'

      - name: Build and run gen_json.go
        run: cd scrape && go run cmd/gen_json.go

      - name: Save output files 1/4
        uses: actions/upload-artifact@master
        with:
          name: result.db
          path: scrape/result.db

      - name: Save output files 2/4
        uses: actions/upload-artifact@master
        with:
          name: ranks_result.json
          path: scrape/ranks_result.json


      - name: Save output files 3/4
        uses: actions/upload-artifact@master
        with:
          name: detailed_result.json
          path: scrape/detailed_result.json

      - name: Save output files 4/4
        uses: actions/upload-artifact@master
        with:
          name: result_config.json
          path: scrape/result_config.json

      - name: copy json files appropriately 1/3
        run: \cp -rf scrape/ranks_result.json web-app/static/ranks_result.json;
      - name: copy json files appropriately 2/3
        run: \cp -rf scrape/detailed_result.json web-app/static/detailed_result.json;
      - name: copy json files appropriately 3/3
        run: \cp -rf scrape/result_config.json web-app/static/result_config.json;
      - name: stage changed files
        run:
          git add scrape/result.db;
          git add scrape/ranks_result.json;
          git add scrape/detailed_result.json;
          git add scrape/result_config.json;
          git add web-app/static/ranks_result.json;
          git add web-app/static/detailed_result.json;
          git add web-app/static/result_config.json;
          git status -v;
      - name: commit changed files
        run:
          git config user.email "actions@github.com";
          git config user.name "Github Actions";
          git commit -m "Updated data"

      - name: push code to master
        run:
          git push;