name: Update branch for a roll name
on:
  workflow_dispatch:
    inputs:
      roll_number:
        description: 'Roll number for which the branch is changed'
        required: true
      branch_name:
        type: choice
        description: 'New branch name'
        required: true
        options:
        - bce(Civil)
        - bee(Electrical)
        - bme(Mechanical)
        - bec(Electronics)
        - bcs(Computer Science)
        - bar(Architecture)
        - bch(Chemical)
        - bms(Material)
        - bph(Engineering Physics)
        - dec(Electronics Dual)
        - dcs(Computer Science Dual)
        - bma(Maths & Computing)

run-name: Update branch for roll number ${{ inputs.roll_number }} to ${{ inputs.branch_name }}


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  run-go-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'


      - name: Build and run update_branch_in_db.go
        run: cd scrape && go run cmd/update_branch_in_db.go '${{ github.event.inputs.roll_number }}' '${{ github.event.inputs.branch_name }}'

      - name: Build and run gen_json.go
        run: cd scrape && go run cmd/gen_json.go

      - name: Save output files 1/4
        uses: actions/upload-artifact@master
        with:
          name: result.db
          path: scrape/result.db

      - name: Save output files 2/4
        uses: actions/upload-artifact@master
        with:
          name: ranks_result.json
          path: scrape/ranks_result.json


      - name: Save output files 3/4
        uses: actions/upload-artifact@master
        with:
          name: detailed_result.json
          path: scrape/detailed_result.json

      - name: Save output files 4/4
        uses: actions/upload-artifact@master
        with:
          name: result_config.json
          path: scrape/result_config.json

      - name: copy json files appropriately 1/3
        run: \cp -rf scrape/ranks_result.json web-app/static/ranks_result.json;
      - name: copy json files appropriately 2/3
        run: \cp -rf scrape/detailed_result.json web-app/static/detailed_result.json;
      - name: copy json files appropriately 3/3
        run: \cp -rf scrape/result_config.json web-app/static/result_config.json;
      - name: stage changed files
        run:
          git add scrape/result.db;
          git add scrape/ranks_result.json;
          git add scrape/detailed_result.json;
          git add scrape/result_config.json;
          git add web-app/static/ranks_result.json;
          git add web-app/static/detailed_result.json;
          git add web-app/static/result_config.json;
          git status -v;
      - name: commit changed files
        run:
          git config user.email "actions@github.com";
          git config user.name "Github Actions";
          git commit -m "Updated branch for roll no ${{ github.event.inputs.roll_number }}"

      - name: push code to master
        run:
          git push;